export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  NUTRITIONIST: 'NUTRITIONIST',
  ADMIN: 'ADMIN',
  PHARMACY_PARTNER: 'PHARMACY_PARTNER'
};

export const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION'
};
